version: '3'
services:
  telegram-bot:
    container_name: telegram-bot
    pid: host
    privileged: true
    network_mode: bridge
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
      - 10003:10003
      - 10004:10004
    environment:
      TZ: Asia/Shanghai
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
