version: '3'
services:
  telegram-bot:
    image: ghcr.io/nichuanfang/telegram-bot:latest
    container_name: telegram-bot
    pid: host
    privileged: true
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    volumes:
      - .:/app
    restart: unless-stopped
