version: '3'
services:
  telegram-bot:
    container_name: telegram-gpt_bot
    pid: host
    privileged: true
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
