version: '3'
services:
  telegram-bot:
    image: ghcr.io/nichuanfang/telegram-bot:latest
    container_name: telegram-bot
    pid: host
    privileged: true
    network_mode: host
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - .:/app
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.4.4
