version: '3'
services:
  telegram-bot:
    container_name: telegram-bot
    pid: host
    privileged: true
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
