name: sync cf cookie

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chrome browser
        run: |
          choco install googlechrome --ignore-checksums --ignore-dependencies -y

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          cache: pip

      - name: Install SeleniumBase
        run: |
          python -m pip install -U seleniumbase

      - name: Sync Cloudflare Cookie
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python sync_cf_cookie.py
